"""
db_offsite_backup.py — an encrypted copy of the Postgres database in Cloud
Storage, and the way back (ToDo: "Database backups").

Neon keeps 7 days of point-in-time restore; this is the second line, off
Neon, kept 90 days by the bucket's lifecycle rule:

    python db_offsite_backup.py backup
        env: DATABASE_URL, BACKUP_BUCKET (e.g. cheapcadtools-backups), BACKUP_KEY
    python db_offsite_backup.py restore <gs-object-or-file> <target DATABASE_URL>
        env: BACKUP_KEY (and BACKUP_BUCKET for a gs object name)
    python db_offsite_backup.py newkey          # print a fresh BACKUP_KEY
    python db_offsite_backup.py replay-order <paypal|stripe> <order id> <email> <tokens> <cents> <payment ref>
        env: DATABASE_URL — a purchase newer than the restored backup

Meant to run as a Cloud Run job (same image, this command) on a daily Cloud
Scheduler trigger. It authenticates to Cloud Storage as the job's own
service account (results.GcsResults: no key file) and reads BACKUP_KEY from
Secret Manager. The key never goes in the bucket; losing it loses the
backups, so keep a second copy of it offline.

What a backup is: one zip — manifest.json (when, from where, row counts),
schema.sql (every table in the database's schema, rebuilt from the
catalog: columns, identity columns, constraints, indexes) and one CSV per
table — encrypted whole with Fernet (AES-128-CBC + HMAC-SHA256). Plain
Python + psycopg: the image has no pg_dump, and a pg_dump would have to
match Neon's server version.

Restore writes into an EMPTY database or schema (it refuses otherwise),
loads every table, and moves each identity counter past the rows it
restored. The procedure around it — including replaying payment-provider
orders newer than the backup — is in RESTORE.md.
"""
from __future__ import annotations

import csv
import io
import json
import os
import re
import sys
import time
import zipfile

FORMAT = 1


# ── dump ──────────────────────────────────────────────────────────────────

def _tables(db) -> list[str]:
    return [r[0] for r in db.execute(
        "SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace "
        "WHERE n.nspname = current_schema() AND c.relkind = 'r' ORDER BY c.relname")]


def _qi(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def _table_ddl(db, table: str) -> list[str]:
    """CREATE TABLE (columns, identity, constraints) and its other indexes."""
    cols = []
    for name, typ, notnull, default, identity in db.execute(
            """SELECT a.attname, pg_catalog.format_type(a.atttypid, a.atttypmod), a.attnotnull,
                      pg_get_expr(d.adbin, d.adrelid), a.attidentity
               FROM pg_attribute a LEFT JOIN pg_attrdef d
                    ON d.adrelid = a.attrelid AND d.adnum = a.attnum
               WHERE a.attrelid = %s::regclass AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum""", (_qi(table),)):
        col = f"{_qi(name)} {typ}"
        if identity == "d":
            col += " GENERATED BY DEFAULT AS IDENTITY"
        elif identity == "a":
            col += " GENERATED ALWAYS AS IDENTITY"
        elif default is not None:
            col += f" DEFAULT {default}"
        if notnull:
            col += " NOT NULL"
        cols.append(col)
    constraints = list(db.execute(
        "SELECT conname, pg_get_constraintdef(oid) FROM pg_constraint "
        "WHERE conrelid = %s::regclass ORDER BY conname", (_qi(table),)))
    for name, definition in constraints:
        cols.append(f"CONSTRAINT {_qi(name)} {definition}")
    ddl = [f"CREATE TABLE {_qi(table)} (\n  " + ",\n  ".join(cols) + "\n);"]
    backing = {name for name, _ in constraints}
    # indexdef always names the schema ("ON myschema.tbl"); drop it so the
    # index restores into whatever schema is current, like the tables
    schema = db.execute("SELECT quote_ident(current_schema())").fetchone()[0]
    qualified = re.compile(r"\bON (ONLY )?" + re.escape(schema) + r"\.")
    for name, definition in db.execute(
            "SELECT indexname, indexdef FROM pg_indexes "
            "WHERE schemaname = current_schema() AND tablename = %s ORDER BY indexname", (table,)):
        if name not in backing:          # constraint indexes come with their constraint
            ddl.append(qualified.sub(lambda m: "ON " + (m.group(1) or ""), definition, count=1) + ";")
    return ddl


def dump(url: str, clock=time.time) -> bytes:
    """The whole database schema as a zip (not encrypted)."""
    import psycopg
    buf = io.BytesIO()
    with psycopg.connect(url) as db, zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        db.execute("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY")  # one snapshot
        tables = _tables(db)
        schema, counts = [], {}
        for t in tables:
            schema += _table_ddl(db, t)
            out = io.StringIO()
            with db.cursor().copy(f"COPY {_qi(t)} TO STDOUT WITH (FORMAT csv, HEADER true)") as cp:
                for chunk in cp:
                    out.write(bytes(chunk).decode("utf-8"))
            z.writestr(f"data/{t}.csv", out.getvalue())
            counts[t] = db.execute(f"SELECT COUNT(*) FROM {_qi(t)}").fetchone()[0]
        z.writestr("schema.sql", "\n\n".join(schema) + "\n")
        z.writestr("manifest.json", json.dumps({
            "format": FORMAT, "created_at": clock(),
            "created_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(clock())),
            "source": _describe(url), "tables": counts}, indent=1))
    return buf.getvalue()


def _describe(url: str) -> str:
    """host/database only — never the password."""
    from urllib.parse import urlsplit
    u = urlsplit(url)
    return f"{u.hostname or '?'}{u.path or ''}"


# ── encryption ────────────────────────────────────────────────────────────

def new_key() -> str:
    from cryptography.fernet import Fernet
    return Fernet.generate_key().decode()


def encrypt(data: bytes, key: str) -> bytes:
    from cryptography.fernet import Fernet
    return Fernet(key.encode()).encrypt(data)


def decrypt(token: bytes, key: str) -> bytes:
    from cryptography.fernet import Fernet
    return Fernet(key.encode()).decrypt(token)


# ── restore ───────────────────────────────────────────────────────────────

def restore(archive: bytes, url: str) -> dict:
    """Load an (unencrypted) backup zip into an empty database/schema.
    Returns the manifest's table row counts, checked against what loaded."""
    import psycopg
    with zipfile.ZipFile(io.BytesIO(archive)) as z:
        manifest = json.loads(z.read("manifest.json"))
        if manifest.get("format") != FORMAT:
            raise ValueError(f"unknown backup format {manifest.get('format')!r}")
        schema = z.read("schema.sql").decode("utf-8")
        with psycopg.connect(url) as db:
            existing = _tables(db)
            if existing:
                raise RuntimeError(f"target is not empty ({len(existing)} tables): restore "
                                   "into a new database or schema")
            db.execute(schema)
            loaded = {}
            for t, expected in manifest["tables"].items():
                data = z.read(f"data/{t}.csv").decode("utf-8")
                if data:
                    header = next(csv.reader(io.StringIO(data)))
                    cols = ", ".join(_qi(c) for c in header)
                    with db.cursor().copy(f"COPY {_qi(t)} ({cols}) FROM STDIN "
                                          "WITH (FORMAT csv, HEADER true)") as cp:
                        cp.write(data.encode("utf-8"))
                loaded[t] = db.execute(f"SELECT COUNT(*) FROM {_qi(t)}").fetchone()[0]
                if loaded[t] != expected:
                    raise RuntimeError(f"{t}: loaded {loaded[t]} rows, backup has {expected}")
            # identity counters: past the highest restored id
            for t, col in db.execute(
                    "SELECT c.relname, a.attname FROM pg_attribute a "
                    "JOIN pg_class c ON c.oid = a.attrelid "
                    "JOIN pg_namespace n ON n.oid = c.relnamespace "
                    "WHERE n.nspname = current_schema() AND a.attidentity IN ('a', 'd')").fetchall():
                db.execute(f"SELECT setval(pg_get_serial_sequence(%s, %s), "
                           f"GREATEST(COALESCE(MAX({_qi(col)}), 0), 1), MAX({_qi(col)}) IS NOT NULL) "
                           f"FROM {_qi(t)}", (_qi(t), col))
    return loaded


# ── after a restore: purchases newer than the backup ─────────────────────

def replay_order(url: str, provider: str, order_id: str, email: str, tokens_: int, cents: int,
                 payment_ref: str) -> bool:
    """Re-enter one token-pack purchase the backup is too old to hold (from
    the PayPal/Stripe dashboard): the order, then its credit, exactly as the
    payment webhook would. Idempotent on the order (a second run credits
    nothing). Returns True if it credited. RESTORE.md step 5."""
    from cct_common.payments import Pack, Payments
    from cct_common.tokens import TokenStore
    store = TokenStore(url)
    acct = store.account_by_email(email) or store.get_or_create_account(email, signup_grant=0)
    pay = Payments(store)
    if pay.get(provider, order_id) is None:
        pay.record(provider, order_id, acct, Pack(provider, int(cents), int(tokens_)))
    return pay.complete(provider, order_id, paid_cents=int(cents), currency="USD",
                        payment_ref=payment_ref)


# ── Cloud Storage ─────────────────────────────────────────────────────────

def object_name(clock=time.time) -> str:
    return time.strftime("postgres/%Y/%m/%d/cct-%Y%m%dT%H%M%SZ.zip.enc", time.gmtime(clock()))


def backup(url: str, bucket_client, key: str, clock=time.time) -> tuple[str, dict]:
    """Dump, encrypt, upload. Returns (object name, table row counts)."""
    archive = dump(url, clock=clock)
    manifest = json.loads(zipfile.ZipFile(io.BytesIO(archive)).read("manifest.json"))
    name = object_name(clock)
    bucket_client.save(name, encrypt(archive, key), "application/octet-stream")
    return name, manifest["tables"]


def _env(name: str) -> str:
    v = os.environ.get(name, "").strip()
    if not v:
        raise SystemExit(f"{name} is not set")
    return v


def main(argv: list[str]) -> int:
    cmd = argv[1] if len(argv) > 1 else ""
    if cmd == "newkey":
        print(new_key())
        return 0
    if cmd == "backup":
        from results import GcsResults
        name, counts = backup(_env("DATABASE_URL"), GcsResults(_env("BACKUP_BUCKET")), _env("BACKUP_KEY"))
        print(f"backed up {sum(counts.values())} rows in {len(counts)} tables to "
              f"gs://{os.environ['BACKUP_BUCKET']}/{name}")
        return 0
    if cmd == "restore" and len(argv) == 4:
        source, target = argv[2], argv[3]
        if os.path.exists(source):
            token = open(source, "rb").read()
        else:
            from results import GcsResults
            token = GcsResults(_env("BACKUP_BUCKET")).load(source, max_age_s=float("inf"))
            if token is None:
                raise SystemExit(f"no such backup: {source}")
        loaded = restore(decrypt(token, _env("BACKUP_KEY")), target)
        print(f"restored {sum(loaded.values())} rows in {len(loaded)} tables")
        return 0
    if cmd == "replay-order" and len(argv) == 8:
        provider, order_id, email, tokens_, cents, ref = argv[2:8]
        credited = replay_order(_env("DATABASE_URL"), provider, order_id, email, int(tokens_),
                                int(cents), ref)
        print(f"{provider} {order_id}: " + ("credited" if credited else "already there — nothing to do"))
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
