services:
  - type: web
    name: pulleywebapp
    env: python
    buildCommand: apt-get install -y libcairo2 && pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn.conf.py
    pythonVersion: "3.12"
