"""
test_db_offsite_backup.py — the encrypted off-site copy of the database
round-trips: dump → encrypt → (bucket) → decrypt → restore gives back every
row of every table, in a fresh schema, with identity counters past the
restored ids.

Needs a Postgres (the stores' Postgres dialect is what production runs):
    CCT_TEST_POSTGRES=postgresql://postgres:cctlocal@127.0.0.1:55432/cct pytest tests/test_db_offsite_backup.py
Skipped without it.
"""
import io
import json
import os
import uuid
import zipfile

import pytest

PG = os.environ.get("CCT_TEST_POSTGRES", "").strip()
pytestmark = pytest.mark.skipif(not PG, reason="needs CCT_TEST_POSTGRES")

import db_offsite_backup as bk  # noqa: E402


@pytest.fixture
def schemas():
    """Two fresh schemas (source, target) as URLs; dropped after."""
    psycopg = pytest.importorskip("psycopg")
    names = ["bk_" + uuid.uuid4().hex[:10] for _ in range(2)]
    with psycopg.connect(PG, autocommit=True) as c:
        for n in names:
            c.execute(f"CREATE SCHEMA {n}")
    sep = "&" if "?" in PG else "?"
    urls = [f"{PG}{sep}options=-csearch_path%3D{n}" for n in names]
    yield urls
    from cct_common.sqlite_db import close_pool
    for u in urls:
        close_pool(u)
    with psycopg.connect(PG, autocommit=True) as c:
        for n in names:
            c.execute(f"DROP SCHEMA {n} CASCADE")


def _fill(url):
    """The app's own stores, with some awkward data."""
    from bug_store import BugReports
    from cct_common.accounts import AccountStore
    from cct_common.payments import Pack, Payments
    from cct_common.tokens import TokenStore
    tokens = TokenStore(url, app="pulleys")
    accounts = AccountStore(tokens, signup_grant=20)
    a = accounts.sign_in("email", "a@example.com", "a@example.com", email_verified=True)
    b = accounts.sign_in("email", "b@example.com", "b@example.com", email_verified=True)
    with tokens.charge(a, "k1", "stl"):
        pass
    tokens.credit(b, 5, kind="promo", detail='line one\nline "two", with commas; and ünïcode')
    pay = Payments(tokens)
    pay.record("paypal", "ORDER-1", b, Pack("paypal", 500, 50))
    pay.complete("paypal", "ORDER-1", paid_cents=500, currency="USD", payment_ref="CAP-1")
    BugReports(url).add("r1", report_type="bug", seeing="x\r\ny", should_see="", error_msg="",
                        user_comment="", email="a@example.com", state={"teeth": 20}, app_version="2")
    accounts.create_session(a, kind="web")
    return tokens


def _rows(url):
    import psycopg
    out = {}
    with psycopg.connect(url) as db:
        for t in bk._tables(db):
            cols = [r[0] for r in db.execute(
                "SELECT column_name FROM information_schema.columns WHERE table_schema = "
                "current_schema() AND table_name = %s ORDER BY ordinal_position", (t,))]
            order = ", ".join(f'"{c}"' for c in cols)
            out[t] = db.execute(f'SELECT * FROM "{t}" ORDER BY {order}').fetchall()
    return out


def test_round_trip_restores_every_row(schemas):
    src, dst = schemas
    _fill(src)
    key = bk.new_key()
    token = bk.encrypt(bk.dump(src, clock=lambda: 1_790_000_000.0), key)
    assert b"a@example.com" not in token                       # encrypted
    loaded = bk.restore(bk.decrypt(token, key), dst)
    before, after = _rows(src), _rows(dst)
    assert set(before) >= {"accounts", "ledger", "payments", "sessions", "bug_reports"}
    assert after == before
    assert loaded == {t: len(r) for t, r in before.items()}


def test_manifest_and_schema(schemas):
    src, _ = schemas
    _fill(src)
    z = zipfile.ZipFile(io.BytesIO(bk.dump(src, clock=lambda: 1_790_000_000.0)))
    m = json.loads(z.read("manifest.json"))
    assert m["format"] == bk.FORMAT and m["created_utc"] == "2026-09-21T14:13:20Z"
    assert "cctlocal" not in json.dumps(m)                     # no password in it
    assert m["tables"]["ledger"] >= 3
    assert "GENERATED BY DEFAULT AS IDENTITY" in z.read("schema.sql").decode()


def test_identity_counters_continue_after_restore(schemas):
    src, dst = schemas
    _fill(src)
    key = bk.new_key()
    bk.restore(bk.decrypt(bk.encrypt(bk.dump(src), key), key), dst)
    from cct_common.tokens import TokenStore
    restored = TokenStore(dst, app="pulleys")
    acct = restored.account_by_email("b@example.com")
    import psycopg
    with psycopg.connect(dst) as db:
        top = db.execute("SELECT MAX(id) FROM ledger").fetchone()[0]
    restored.credit(acct, 1, kind="promo", detail="after restore")
    with psycopg.connect(dst) as db:
        assert db.execute("SELECT MAX(id) FROM ledger").fetchone()[0] > top


def test_restore_refuses_a_database_that_is_not_empty(schemas):
    src, _ = schemas
    _fill(src)
    archive = bk.dump(src)
    with pytest.raises(RuntimeError, match="not empty"):
        bk.restore(archive, src)


def test_wrong_key_is_refused(schemas):
    src, _ = schemas
    _fill(src)
    token = bk.encrypt(bk.dump(src), bk.new_key())
    from cryptography.fernet import InvalidToken
    with pytest.raises(InvalidToken):
        bk.decrypt(token, bk.new_key())


def test_backup_uploads_one_encrypted_object(schemas):
    src, _ = schemas
    _fill(src)

    class Bucket:
        def __init__(self):
            self.saved = {}

        def save(self, name, data, content_type):
            self.saved[name] = (data, content_type)

    bucket, key = Bucket(), bk.new_key()
    name, counts = bk.backup(src, bucket, key, clock=lambda: 1_790_000_000.0)
    assert name == "postgres/2026/09/21/cct-20260921T141320Z.zip.enc"
    data, ctype = bucket.saved[name]
    assert ctype == "application/octet-stream"
    assert json.loads(zipfile.ZipFile(io.BytesIO(bk.decrypt(data, key))).read("manifest.json"))["tables"] == counts


def test_replay_order_after_restore_credits_once(schemas):
    """A purchase newer than the backup is re-entered as the webhook would:
    purchased tokens (refundable), and a second replay credits nothing."""
    src, dst = schemas
    _fill(src)
    key = bk.new_key()
    bk.restore(bk.decrypt(bk.encrypt(bk.dump(src), key), key), dst)
    from cct_common.tokens import TokenStore
    store = TokenStore(dst)
    acct = store.account_by_email("b@example.com")
    before, bought_before = store.balance(acct), store.purchased_remaining(acct)
    assert bk.replay_order(dst, "stripe", "cs_new", "b@example.com", 100, 1000, "pi_new") is True
    assert store.balance(acct) == before + 100
    assert store.purchased_remaining(acct) == bought_before + 100
    assert bk.replay_order(dst, "stripe", "cs_new", "b@example.com", 100, 1000, "pi_new") is False
    assert store.balance(acct) == before + 100
