"""
CheapCADTools SolidWorks Listener
----------------------------------
Watches a temp folder for STEP/DXF files generated by the CCT web app and
auto-imports them into the active SolidWorks document.

Same pattern as the Fusion 360 addin:
  - Writes solidworks_watch_dir + solidworks_connected to config.json on start
  - Clears solidworks_connected on clean exit
  - Flask app mirrors downloads to solidworks_watch_dir when connected
"""

import json
import logging
import os
import sys
import tempfile
import time
import threading
import webbrowser

# ── Third-party (see requirements.txt) ────────────────────────────────────────
try:
    import pystray
    from PIL import Image, ImageDraw
except ImportError:
    sys.exit("Run: pip install pystray Pillow")

try:
    from watchdog.observers import Observer
    from watchdog.events import FileSystemEventHandler
except ImportError:
    sys.exit("Run: pip install watchdog")

try:
    import win32com.client
    import pythoncom
    _HAVE_WIN32 = True
except ImportError:
    _HAVE_WIN32 = False
    logging.warning("pywin32 not installed — SolidWorks import disabled (pip install pywin32)")

# ── Config ─────────────────────────────────────────────────────────────────────
CONFIG_PATH = os.path.join(
    os.environ.get('APPDATA', os.path.expanduser('~')),
    'CheapCADTools', 'config.json'
)
CCT_URL = 'https://cheapcadtools.com/tools/pulleys'
WATCH_EXTS = {'.step', '.stp', '.dxf'}

logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s %(levelname)s %(message)s')
log = logging.getLogger('cct_sw_listener')


# ── Config helpers ─────────────────────────────────────────────────────────────
def _load_config() -> dict:
    try:
        with open(CONFIG_PATH, encoding='utf-8') as f:
            return json.load(f)
    except Exception:
        return {}


def _save_config(cfg: dict) -> None:
    os.makedirs(os.path.dirname(CONFIG_PATH), exist_ok=True)
    with open(CONFIG_PATH, 'w', encoding='utf-8') as f:
        json.dump(cfg, f, indent=2)


# ── SolidWorks import ──────────────────────────────────────────────────────────
def _import_to_solidworks(filepath: str) -> None:
    if not _HAVE_WIN32:
        log.warning("pywin32 missing — cannot import %s", filepath)
        return

    pythoncom.CoInitialize()
    try:
        try:
            swApp = win32com.client.GetActiveObject("SldWorks.Application")
        except Exception:
            log.warning("SolidWorks is not running — cannot import %s", filepath)
            return

        swApp.Visible = True

        # swDocPART=1; swOpenDocOptions_Silent=1; use empty config string
        errors = win32com.client.VARIANT(pythoncom.VT_BYREF | pythoncom.VT_I4, 0)
        warnings = win32com.client.VARIANT(pythoncom.VT_BYREF | pythoncom.VT_I4, 0)
        doc = swApp.OpenDoc6(filepath, 1, 1, "", errors, warnings)

        err_code = errors.value if hasattr(errors, 'value') else 0
        if doc is None or err_code != 0:
            log.error("OpenDoc6 failed for %s (error code %s)", filepath, err_code)
        else:
            log.info("Imported %s into SolidWorks", os.path.basename(filepath))
    finally:
        pythoncom.CoUninitialize()


# ── File watcher ───────────────────────────────────────────────────────────────
class _CCTFileHandler(FileSystemEventHandler):
    def __init__(self, pending: set):
        super().__init__()
        self._pending = pending
        self._lock = threading.Lock()

    def on_created(self, event):
        if event.is_directory:
            return
        path = event.src_path
        if os.path.splitext(path)[1].lower() not in WATCH_EXTS:
            return
        with self._lock:
            if path in self._pending:
                return
            self._pending.add(path)
        # Small delay so the write completes before we try to open it
        threading.Timer(1.0, self._handle, args=(path,)).start()

    def _handle(self, path: str):
        with self._lock:
            self._pending.discard(path)
        if not os.path.exists(path):
            return
        log.info("Detected %s — importing to SolidWorks", os.path.basename(path))
        _import_to_solidworks(path)


# ── Tray icon ──────────────────────────────────────────────────────────────────
def _make_icon() -> Image.Image:
    """Generate a simple red-on-white CCT icon (no external assets needed)."""
    img = Image.new('RGB', (64, 64), color=(255, 255, 255))
    d = ImageDraw.Draw(img)
    d.ellipse([4, 4, 60, 60], fill=(118, 21, 22))   # CCT deep red #761516
    d.ellipse([16, 16, 48, 48], fill=(255, 255, 255))
    d.ellipse([24, 24, 40, 40], fill=(118, 21, 22))
    return img


class _ListenerApp:
    def __init__(self):
        self._watch_dir = os.path.join(tempfile.gettempdir(), 'cct_sw_watch')
        self._observer: Observer | None = None
        self._pending: set = set()
        self._icon: pystray.Icon | None = None

    def _start_watcher(self):
        os.makedirs(self._watch_dir, exist_ok=True)
        handler = _CCTFileHandler(self._pending)
        self._observer = Observer()
        self._observer.schedule(handler, self._watch_dir, recursive=False)
        self._observer.start()
        log.info("Watching %s", self._watch_dir)

    def _stop_watcher(self):
        if self._observer:
            self._observer.stop()
            self._observer.join()
            self._observer = None

    def _write_config(self, connected: bool):
        cfg = _load_config()
        cfg['solidworks_connected'] = connected
        cfg['solidworks_watch_dir'] = self._watch_dir if connected else ''
        _save_config(cfg)

    def _on_open_web_app(self, icon, item):
        webbrowser.open(CCT_URL)

    def _on_exit(self, icon, item):
        log.info("Shutting down")
        self._stop_watcher()
        self._write_config(connected=False)
        icon.stop()

    def run(self):
        self._start_watcher()
        self._write_config(connected=True)
        log.info("SolidWorks listener started — watching %s", self._watch_dir)

        sw_status = "SolidWorks: connected" if _HAVE_WIN32 else "SolidWorks: pywin32 missing"
        menu = pystray.Menu(
            pystray.MenuItem('CheapCADTools — SolidWorks Listener', None, enabled=False),
            pystray.MenuItem(sw_status, None, enabled=False),
            pystray.Menu.SEPARATOR,
            pystray.MenuItem('Open Web App', self._on_open_web_app),
            pystray.Menu.SEPARATOR,
            pystray.MenuItem('Exit', self._on_exit),
        )
        self._icon = pystray.Icon('CCT SolidWorks', _make_icon(), 'CCT SolidWorks', menu)
        try:
            self._icon.run()
        finally:
            self._stop_watcher()
            self._write_config(connected=False)


if __name__ == '__main__':
    _ListenerApp().run()
