"""
sqlite_db.py — the database plumbing shared by cct_common.tokens and
cct_common.accounts (and any app store built on SqliteDB), which live in
one database.

The store's `path` picks the backend:
- a file path  -> SQLite (local runs, tests, a single-server deploy);
- a postgresql:// URL -> PostgreSQL (Cloud Run: no disk, several servers).

The stores' SQL is written once, in the SQLite dialect, and translated for
Postgres here: `?` placeholders, `INSERT OR IGNORE`, `REAL` timestamps
(DOUBLE PRECISION — Postgres REAL is too coarse for epoch seconds) and
`INTEGER PRIMARY KEY AUTOINCREMENT`. Rows support both row["name"] and
row[0] on either backend. Write `RETURNING id`, not `lastrowid`.

Durability and concurrency (see PulleyWebApp-ss ADR-008 "data safety"):
- SQLite: WAL journal + synchronous=FULL; writes take BEGIN IMMEDIATE, so
  a check-then-write sequence (spend the last token) can't interleave
  across workers or processes.
- Postgres: every write transaction first takes one transaction-scoped
  advisory lock, so writes serialise exactly as they do on SQLite — the
  same guarantee across servers. Connections come from a small pool per
  database URL, with server-side prepared statements off so it also works
  behind a transaction-mode pooler (Neon's pooled endpoint, PgBouncer).
- integrity_check() and backup() are the SQLite startup check and the
  scheduled copy; on Postgres the provider's backups (Neon point-in-time
  restore) take backup()'s place.
"""
from __future__ import annotations

import os
import re
import sqlite3
import threading
from contextlib import contextmanager
from typing import Iterator

POSTGRES_PREFIXES = ("postgresql://", "postgres://")
_PG_WRITE_LOCK = 0x4343545F4442   # arbitrary constant key: "CCT_DB"


def is_postgres(path) -> bool:
    return str(path).startswith(POSTGRES_PREFIXES)


def _errors(sqlite_error, pg_name):
    errs = [sqlite_error]
    try:
        import psycopg
        errs.append(getattr(psycopg.errors, pg_name) if pg_name != "Error" else psycopg.Error)
    except ImportError:
        pass
    return tuple(errs)


# Catch these rather than sqlite3's own classes, so a store works on both.
INTEGRITY_ERRORS = _errors(sqlite3.IntegrityError, "IntegrityError")
DB_ERRORS = _errors(sqlite3.DatabaseError, "Error")


# ── Postgres translation and connections ─────────────────────────────────

def _pg_sql(sql: str, has_params: bool) -> str:
    if has_params:
        sql = sql.replace("%", "%%").replace("?", "%s")
    if re.match(r"\s*INSERT\s+OR\s+IGNORE\s+INTO", sql, re.I):
        sql = re.sub(r"INSERT\s+OR\s+IGNORE\s+INTO", "INSERT INTO", sql, count=1, flags=re.I)
        sql = sql.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    return sql


def _pg_ddl(sql: str) -> str:
    sql = re.sub(r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
                 "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql, flags=re.I)
    return re.sub(r"\bREAL\b", "DOUBLE PRECISION", sql)


class Row(tuple):
    """A result row readable by position or by column name, like sqlite3.Row."""

    def __new__(cls, values, names):
        row = super().__new__(cls, values)
        row._names = names
        return row

    def __getitem__(self, key):
        if isinstance(key, str):
            return tuple.__getitem__(self, self._names.index(key))
        return tuple.__getitem__(self, key)

    def keys(self):
        return list(self._names)


def _row_factory(cursor):
    if cursor.description is None:
        return lambda values: values
    names = [d.name for d in cursor.description]
    return lambda values: Row(values, names)


class _PgConnection:
    """Presents a psycopg connection with sqlite3's execute() and SQL dialect."""

    def __init__(self, conn):
        self._conn = conn

    def execute(self, sql: str, params=()):
        params = tuple(params) if params else ()
        return self._conn.execute(_pg_sql(sql, bool(params)), params or None)


_POOLS: dict = {}
_POOLS_LOCK = threading.Lock()


def _pool(url: str):
    with _POOLS_LOCK:
        pool = _POOLS.get(url)
        if pool is None:
            from psycopg_pool import ConnectionPool
            pool = ConnectionPool(
                url, min_size=1, max_size=int(os.environ.get("CCT_DB_POOL_MAX", "8")),
                max_idle=300, open=True,
                kwargs={"autocommit": True, "row_factory": _row_factory,
                        "prepare_threshold": None})
            _POOLS[url] = pool
        return pool


def close_pool(url: str) -> None:
    """Close the connection pool for a database URL (tests, shutdown)."""
    with _POOLS_LOCK:
        pool = _POOLS.pop(url, None)
    if pool is not None:
        pool.close()


# ── the store base class ──────────────────────────────────────────────────

class SqliteDB:
    """Base for stores backed by one database — a SQLite file or a Postgres
    URL. Subclasses pass their schema (SQLite dialect); several stores may
    share a database (schemas use IF NOT EXISTS)."""

    def __init__(self, path: str, schema: str):
        self.path = path
        if self.is_postgres:
            # Under the write lock: several servers starting at once must
            # not race each other creating the same tables.
            with self._write() as db:
                for stmt in _pg_ddl(schema).split(";"):
                    if stmt.strip():
                        db.execute(stmt)
            return
        parent = os.path.dirname(os.path.abspath(path))
        os.makedirs(parent, exist_ok=True)
        with self._read() as db:
            db.execute("PRAGMA journal_mode=WAL")
            db.executescript(schema)

    @property
    def is_postgres(self) -> bool:
        return is_postgres(self.path)

    def _connect(self) -> sqlite3.Connection:
        # isolation_level=None lets us issue BEGIN IMMEDIATE ourselves.
        db = sqlite3.connect(self.path, timeout=30, isolation_level=None)
        db.row_factory = sqlite3.Row
        db.execute("PRAGMA synchronous=FULL")
        db.execute("PRAGMA foreign_keys=ON")
        return db

    @contextmanager
    def _read(self) -> Iterator:
        if self.is_postgres:
            with _pool(self.path).connection() as conn:
                yield _PgConnection(conn)
            return
        db = self._connect()
        try:
            yield db
        finally:
            db.close()

    @contextmanager
    def _write(self) -> Iterator:
        if self.is_postgres:
            with _pool(self.path).connection() as conn:
                with conn.transaction():
                    conn.execute("SELECT pg_advisory_xact_lock(%s)", (_PG_WRITE_LOCK,))
                    yield _PgConnection(conn)
            return
        db = self._connect()
        try:
            db.execute("BEGIN IMMEDIATE")
            try:
                yield db
            except BaseException:
                db.execute("ROLLBACK")
                raise
            db.execute("COMMIT")
        finally:
            db.close()

    def _ensure_columns(self, table: str, columns: dict) -> None:
        """Add columns that a newer version of a schema introduced to a
        database created by an older one ({name: "TYPE ..."})."""
        with self._write() as db:
            if self.is_postgres:
                for name, decl in columns.items():
                    db.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {name} {_pg_ddl(decl)}")
                return
            have = {r["name"] for r in db.execute(f"PRAGMA table_info({table})")}
            for name, decl in columns.items():
                if name not in have:
                    db.execute(f"ALTER TABLE {table} ADD COLUMN {name} {decl}")

    def integrity_check(self) -> list[str]:
        """Problems found in the database; an empty list means healthy.
        Run at startup and refuse to charge if it isn't empty. (On Postgres:
        that the database answers — its storage is the provider's to check.)"""
        try:
            with self._read() as db:
                if self.is_postgres:
                    db.execute("SELECT 1").fetchone()
                    return []
                rows = [r[0] for r in db.execute("PRAGMA integrity_check").fetchall()]
        except DB_ERRORS as e:
            return [str(e)]
        return [] if rows == ["ok"] else rows

    def backup(self, dest_path: str) -> str:
        """Consistent copy of the live SQLite database to dest_path, taken
        without stopping writers (SQLite's online backup API). Returns
        dest_path. Copy the result off the server: a backup on the same disk
        dies with it. Postgres databases are backed up by their provider."""
        if self.is_postgres:
            raise NotImplementedError("Postgres: use the provider's backups "
                                      "(e.g. Neon point-in-time restore)")
        parent = os.path.dirname(os.path.abspath(dest_path))
        os.makedirs(parent, exist_ok=True)
        tmp = dest_path + ".partial"
        src = self._connect()
        try:
            dst = sqlite3.connect(tmp)
            try:
                src.backup(dst)
                # The copy inherits WAL mode from the live file, and a WAL
                # database grows -wal/-shm side files whenever it's opened.
                # A backup should be one self-contained file.
                dst.execute("PRAGMA journal_mode=DELETE")
            finally:
                dst.close()
        finally:
            src.close()
        os.replace(tmp, dest_path)
        return dest_path
